//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

namespace Domain.Order.Printer
{

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PrintRequestInfo
    {

        private PrintRequestInfoEPOSPrint ePOSPrintField;

        /// <remarks/>
        public PrintRequestInfoEPOSPrint ePOSPrint
        {
            get
            {
                return this.ePOSPrintField;
            }
            set
            {
                this.ePOSPrintField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PrintRequestInfoEPOSPrint
    {

        private PrintRequestInfoEPOSPrintParameter parameterField;

        private PrintRequestInfoEPOSPrintPrintData printDataField;

        /// <remarks/>
        public PrintRequestInfoEPOSPrintParameter Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        /// <remarks/>
        public PrintRequestInfoEPOSPrintPrintData PrintData
        {
            get
            {
                return this.printDataField;
            }
            set
            {
                this.printDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PrintRequestInfoEPOSPrintParameter
    {

        private string devidField;

        private ushort timeoutField;

        /// <remarks/>
        public string devid
        {
            get
            {
                return this.devidField;
            }
            set
            {
                this.devidField = value;
            }
        }

        /// <remarks/>
        public ushort timeout
        {
            get
            {
                return this.timeoutField;
            }
            set
            {
                this.timeoutField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PrintRequestInfoEPOSPrintPrintData
    {

        private eposprint eposprintField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("epos-print", Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
        public eposprint eposprint
        {
            get
            {
                return this.eposprintField;
            }
            set
            {
                this.eposprintField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
    [System.Xml.Serialization.XmlRootAttribute("epos-print", Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print", IsNullable = false)]
    public partial class eposprint
    {

        private List<object> itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cut", typeof(eposprintCut))]
        [System.Xml.Serialization.XmlElementAttribute("feed", typeof(eposprintFeed))]
        [System.Xml.Serialization.XmlElementAttribute("sound", typeof(eposprintSound))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(eposprintText))]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
    public partial class eposprintCut
    {

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
    public partial class eposprintFeed
    {

        private byte unitField;

        private bool unitFieldSpecified;

        private byte lineField;

        private bool lineFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified
        {
            get
            {
                return this.unitFieldSpecified;
            }
            set
            {
                this.unitFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte line
        {
            get
            {
                return this.lineField;
            }
            set
            {
                this.lineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineSpecified
        {
            get
            {
                return this.lineFieldSpecified;
            }
            set
            {
                this.lineFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
    public partial class eposprintSound
    {

        private string patternField;

        private byte repeatField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern
        {
            get
            {
                return this.patternField;
            }
            set
            {
                this.patternField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte repeat
        {
            get
            {
                return this.repeatField;
            }
            set
            {
                this.repeatField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.epson-pos.com/schemas/2011/03/epos-print")]
    public partial class eposprintText
    {

        private string langField;

        private bool smoothField;

        private bool smoothFieldSpecified;

        private string alignField;

        private string fontField;

        private byte widthField;

        private bool widthFieldSpecified;

        private byte heightField;

        private bool heightFieldSpecified;

        private bool reverseField;

        private bool reverseFieldSpecified;

        private bool ulField;

        private bool ulFieldSpecified;

        private bool emField;

        private bool emFieldSpecified;

        private string colorField;

        private ushort xField;

        private bool xFieldSpecified;

        private ushort yField;

        private bool yFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool smooth
        {
            get
            {
                return this.smoothField;
            }
            set
            {
                this.smoothField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smoothSpecified
        {
            get
            {
                return this.smoothFieldSpecified;
            }
            set
            {
                this.smoothFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string align
        {
            get
            {
                return this.alignField;
            }
            set
            {
                this.alignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string font
        {
            get
            {
                return this.fontField;
            }
            set
            {
                this.fontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified
        {
            get
            {
                return this.widthFieldSpecified;
            }
            set
            {
                this.widthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified
        {
            get
            {
                return this.heightFieldSpecified;
            }
            set
            {
                this.heightFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool reverse
        {
            get
            {
                return this.reverseField;
            }
            set
            {
                this.reverseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reverseSpecified
        {
            get
            {
                return this.reverseFieldSpecified;
            }
            set
            {
                this.reverseFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ul
        {
            get
            {
                return this.ulField;
            }
            set
            {
                this.ulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ulSpecified
        {
            get
            {
                return this.ulFieldSpecified;
            }
            set
            {
                this.ulFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool em
        {
            get
            {
                return this.emField;
            }
            set
            {
                this.emField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emSpecified
        {
            get
            {
                return this.emFieldSpecified;
            }
            set
            {
                this.emFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified
        {
            get
            {
                return this.xFieldSpecified;
            }
            set
            {
                this.xFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified
        {
            get
            {
                return this.yFieldSpecified;
            }
            set
            {
                this.yFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }


}
